apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-router
  annotations:
    kubernetes.io/ingress.class: nginx
    # If using cert-manager later, add:
    # cert-manager.io/cluster-issuer: letsencrypt
spec:
  # tls:
  # - hosts: [your.domain.com]
  #   secretName: tls-your-domain
  rules:
  - # host: your.domain.com  # add when you have DNS; omit for test by IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend: { service: { name: web-landing, port: { number: 80 } } }
      - path: /aws
        pathType: Prefix
        backend: { service: { name: web-aws, port: { number: 80 } } }
      - path: /azure
        pathType: Prefix
        backend: { service: { name: web-azure, port: { number: 80 } } }
      - path: /gcp
        pathType: Prefix
        backend: { service: { name: web-gcp, port: { number: 80 } } }
